# Generated by Django 4.1.7 on 2023-04-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='confirm_password',
            field=models.CharField(default='c', max_length=50),
            preserve_default=False,
        ),
    ]
